//
// "$Id: main_panel.fl 01 2018-03-29 18:21:11Z gsergia $"
//
// FLUID template support for the Fast Light Tool Kit (FLTK).
//
// Copyright 1998-2016 by Bill Spitzak and others.
//
// This library is free software. Distribution and use rights are outlined in
// the file "COPYING" which should have been included with this file.  If this
// file is missing or damaged, see the license at:
//
//     http://www.fltk.org/COPYING.php
//
// Please report all bugs and problems on the following page:
//
//     http://www.fltk.org/str.php
//

// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef main_panel_h
#define main_panel_h
#include <FL/Fl.H>

/**
 Main window class
*/
class MainWnd : public FL_Single_Window {
public:
  void make_main_panel();
};
extern MainWnd *main_panel;
#include <FL/Fl_Text_Editor.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Pack.H>
#include <FL/Fl_Slider.H>
MainWnd* make_main_panel();
#endif

//
// End of "$Id:  main_panel.fl 01 2018-03-29 18:21:11Z gsergia $".
//
