//
// "$Id: main_panel.fl 01 2018-03-29 18:21:11Z gsergia $"
//
// FLUID template support for the Fast Light Tool Kit (FLTK).
//
// Copyright 1998-2016 by Bill Spitzak and others.
//
// This library is free software. Distribution and use rights are outlined in
// the file "COPYING" which should have been included with this file.  If this
// file is missing or damaged, see the license at:
//
//     http://www.fltk.org/COPYING.php
//
// Please report all bugs and problems on the following page:
//
//     http://www.fltk.org/str.php
//

// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef main_panel_h
#define main_panel_h

#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Slider.H>
#include <FL/fl_ask.H>
#include <Fl/Fl_Box.H>


/**
 Main window class
*/

namespace cvtool
{
  class UIController;
  class MainWnd : public Fl_Double_Window 
  {
      UIController* pController;
      
      public:
          MainWnd(int X, int Y, int W, int H, const char* l = 0);
          void SetUIController(UIController* controller);
  };
}

#endif

//
// End of "$Id:  main_panel.fl 01 2018-03-29 18:21:11Z gsergia $".
//
