//
// "$Id: main_panel.fl 01 2018-03-29 18:21:11Z gsergia $"
//
// FLUID template support for the Fast Light Tool Kit (FLTK).
//
// Copyright 1998-2016 by Bill Spitzak and others.
//
// This library is free software. Distribution and use rights are outlined in
// the file "COPYING" which should have been included with this file.  If this
// file is missing or damaged, see the license at:
//
//     http://www.fltk.org/COPYING.php
//
// Please report all bugs and problems on the following page:
//
//     http://www.fltk.org/str.php
//

// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include <main_panel.h>
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <ui_controller.h>
#include <FL/filename.H>
#include <FL/fl_ask.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Preferences.H>
#include <thumbnail_widget.h>

#if defined(WIN32) && !defined(__CYGWIN__)
#include <io.h>
#else
#include <unistd.h>
#endif // WIN32 && !__CYGWIN__
extern Fl_Preferences fluid_prefs;

using namespace cvtool;

MainWnd::MainWnd(int X, int Y, int W, int H, const char* l) :
  Fl_Double_Window(X, Y, W, H, l)
{

}

void MainWnd::SetUIController(UIController* controller)
{
    pController = controller;
}

//
// End of "$Id:  main_panel.fl 01 2018-03-29 18:21:11Z gsergia $".
//
